package com.tirocinio.Composer.service;

import org.springframework.stereotype.Service;
import java.time.LocalDate;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class ComposerService {

    public String composeConfiguration(Map<String, String> fragments) {

        // --- Normalizzazione frammenti (rimuove BOM, whitespace, caratteri invisibili) ---
        String weatherFragment  = normalize(fragments.getOrDefault("weatherFragment", ""));
        String vehicleFragment  = normalize(fragments.getOrDefault("vehicleFragment", ""));
        String scenarioFragment = normalize(fragments.getOrDefault("scenarioFragment", ""));

        // --- Estrazione sezioni ---
        String roadNetwork     = extractSection(scenarioFragment, "RoadNetwork");
        String egoObject       = extractScenarioObject(vehicleFragment);
        String trafficObjects  = extractTrafficObjects(scenarioFragment);
        String weatherAction   = wrapWeather(weatherFragment);
        String egoInit         = extractInitPrivate(vehicleFragment);
        String trafficInit     = extractInitPrivate(scenarioFragment);

        // --- Composizione XML finale ---
        StringBuilder xml = new StringBuilder();

        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<OpenSCENARIO>\n");
        xml.append("  <FileHeader revMajor=\"1\" revMinor=\"0\" date=\"")
                .append(LocalDate.now())
                .append("\" description=\"CARLA Scenario generated by CarlaConfigHub\" author=\"CarlaConfigHub\"/>\n\n");

        // RoadNetwork
        xml.append("  <RoadNetwork>\n")
                .append(indent(roadNetwork, 4)).append("\n")
                .append("  </RoadNetwork>\n\n");

        // Entities
        xml.append("  <Entities>\n");
        xml.append(indent(egoObject, 4)).append("\n");
        xml.append(indent(trafficObjects, 4)).append("\n");
        xml.append("  </Entities>\n\n");

        // Storyboard
        xml.append("  <Storyboard>\n");
        xml.append("    <Init>\n");
        xml.append("      <Actions>\n");

        xml.append(indent(weatherAction, 8)).append("\n");
        xml.append(indent(egoInit, 8)).append("\n");
        xml.append(indent(trafficInit, 8)).append("\n");

        xml.append("      </Actions>\n");
        xml.append("    </Init>\n");

        xml.append("    <Story name=\"MainStory\">\n");
        xml.append("      <Act name=\"DefaultAct\"/>\n");
        xml.append("    </Story>\n");

        xml.append("  </Storyboard>\n");
        xml.append("</OpenSCENARIO>");

        return clean(xml.toString());
    }

    // -------------------------------------------------------------------------
    // ----------------------------- HELPERS -----------------------------------
    // -------------------------------------------------------------------------

    /** Normalizza il frammento eliminando BOM, whitespace e caratteri invisibili */
    private String normalize(String xml) {
        if (xml == null) return "";
        return xml
                .replace("\uFEFF", "")
                .replaceAll("^[\\s\\u0000-\\u001F]+", "")
                .trim();
    }


    private String extractSection(String xml, String tag) {
        if (xml == null) return "";
        Pattern p = Pattern.compile("<" + tag + "[^>]*>([\\s\\S]*?)</" + tag + ">");
        Matcher m = p.matcher(xml);
        return m.find() ? m.group(1).trim() : "";
    }

    /** Estrae SOLO il blocco <ScenarioObject> dell’EgoVehicle */
    private String extractScenarioObject(String xml) {
        if (xml == null) return "";
        Pattern p = Pattern.compile("<ScenarioObject[^>]*>[\\s\\S]*?</ScenarioObject>");
        Matcher m = p.matcher(xml);
        return m.find() ? m.group(0).trim() : "";
    }

    /** Estrae TUTTI i TrafficVehicle_x */
    private String extractTrafficObjects(String xml) {
        if (xml == null) return "";
        StringBuilder sb = new StringBuilder();

        Pattern p = Pattern.compile("<ScenarioObject[^>]*>[\\s\\S]*?</ScenarioObject>");
        Matcher m = p.matcher(xml);

        while (m.find()) {
            String block = m.group(0);
            if (!block.contains("EgoVehicle")) {
                sb.append(block).append("\n");
            }
        }
        return sb.toString().trim();
    }

    /** Incapsula il blocco <Weather> dentro GlobalAction */
    private String wrapWeather(String weather) {
        if (weather == null || weather.isBlank()) return "";

        return """
        <GlobalAction>
          <EnvironmentAction>
            <Environment>
        """ + indent(weather, 14) + """
            </Environment>
          </EnvironmentAction>
        </GlobalAction>
        """;
    }

    /** Estrae tutti i blocchi <Private> */
    private String extractInitPrivate(String xml) {
        if (xml == null) return "";
        StringBuilder sb = new StringBuilder();

        Pattern p = Pattern.compile("<Private[\\s\\S]*?</Private>");
        Matcher m = p.matcher(xml);

        while (m.find()) sb.append(m.group(0)).append("\n");

        return sb.toString().trim();
    }

    private String indent(String text, int spaces) {
        if (text == null || text.isBlank()) return "";
        String pad = " ".repeat(spaces);
        return text.replaceAll("(?m)^", pad);
    }

    private String clean(String xml) {
        return xml.replaceAll("(?m)^[ \t]*\r?\n", "");
    }
}
