package com.tirocinio.Composer.service;


import org.springframework.stereotype.Service;
import java.time.LocalDate;
import org.w3c.dom.Document;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.StringReader;
import java.util.Map;

@Service
public class ComposerService {

    public String composeConfiguration(Map<String, String> fragments) {

        String weatherFragment = fragments.getOrDefault("weatherFragment", "");
        String vehicleFragment = fragments.getOrDefault("vehicleFragment", "");
        String scenarioFragment = fragments.getOrDefault("scenarioFragment", "");

        StringBuilder xml = new StringBuilder();

        // Header XML
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<OpenSCENARIO>\n");

        // FileHeader
        xml.append("  <FileHeader revMajor=\"1\" revMinor=\"0\" ")
                .append("date=\"").append(LocalDate.now()).append("\" ")
                .append("description=\"CARLA Scenario generated by CarlaConfigHub\" ")
                .append("author=\"CarlaConfigHub\"/>\n\n");

        // RoadNetwork + Traffic/Pedestrians GlobalAction
        xml.append(indent(extractRoadNetwork(scenarioFragment), 2)).append("\n\n");

        // Entities (Vehicle)
        xml.append("  <Entities>\n");
        xml.append(indent(extractScenarioObject(vehicleFragment), 4)).append("\n");
        xml.append("  </Entities>\n\n");

        // Storyboard
        xml.append("  <Storyboard>\n");
        xml.append("    <Init>\n");
        xml.append("      <Actions>\n");

        // Weather
        xml.append(indent(weatherFragment, 8)).append("\n");

        // Traffic + Pedestrians
        xml.append(indent(extractGlobalActions(scenarioFragment), 8)).append("\n");

        // Autopilot
        xml.append(indent(extractPrivateActions(vehicleFragment), 8)).append("\n");

        xml.append("      </Actions>\n");
        xml.append("    </Init>\n");

        // Story (obbligatorio in OpenSCENARIO)
        xml.append("    <Story name=\"MainStory\">\n");
        xml.append("      <Act name=\"DefaultAct\"/>\n");
        xml.append("    </Story>\n");

        xml.append("  </Storyboard>\n");
        xml.append("</OpenSCENARIO>");

        String result = xml.toString();

        if (!isValidXml(result)) {
            throw new RuntimeException("L'XML generato non è valido o è corrotto.");
        }

        return result;
    }

    // ---------------- Helper ----------------

    private boolean isValidXml(String xmlString) {
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setNamespaceAware(true);
            factory.setIgnoringComments(true);
            factory.setCoalescing(true);
            factory.setIgnoringElementContentWhitespace(true);

            DocumentBuilder builder = factory.newDocumentBuilder();
            builder.parse(new InputSource(new StringReader(xmlString)));
            return true;
        } catch (Exception e) {
            System.err.println("Validazione XML fallita: " + e.getMessage());
            return false;
        }
    }

    private String indent(String xml, int spaces) {
        if (xml == null || xml.isBlank()) return "";
        String pad = " ".repeat(spaces);

        // Non indentare dentro CDATA
        if (xml.contains("<![CDATA[")) return pad + xml;

        return xml.replaceAll("(?m)^", pad);
    }

    private String extractRoadNetwork(String scenarioFragment) {
        if (scenarioFragment.contains("<RoadNetwork>")) {
            return scenarioFragment.substring(
                    scenarioFragment.indexOf("<RoadNetwork>"),
                    scenarioFragment.indexOf("</RoadNetwork>") + "</RoadNetwork>".length()
            );
        }
        return "";
    }

    private String extractScenarioObject(String vehicleFragment) {
        if (vehicleFragment.contains("<ScenarioObject")) {
            return vehicleFragment.substring(
                    vehicleFragment.indexOf("<ScenarioObject"),
                    vehicleFragment.indexOf("</ScenarioObject>") + "</ScenarioObject>".length()
            );
        }
        return "";
    }

    private String extractGlobalActions(String scenarioFragment) {
        if (scenarioFragment.contains("<GlobalAction>")) {
            return scenarioFragment.substring(
                    scenarioFragment.indexOf("<GlobalAction>"),
                    scenarioFragment.lastIndexOf("</GlobalAction>") + "</GlobalAction>".length()
            );
        }
        return "";
    }

    private String extractPrivateActions(String vehicleFragment) {
        if (vehicleFragment.contains("<Private")) {
            return vehicleFragment.substring(
                    vehicleFragment.indexOf("<Private"),
                    vehicleFragment.lastIndexOf("</Private>") + "</Private>".length()
            );
        }
        return "";
    }
}
