package com.tirocinio.Composer.service;

import org.springframework.stereotype.Service;
import java.time.LocalDate;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class ComposerService {

    public String composeConfiguration(Map<String, String> fragments) {

        String weatherFragment = fragments.getOrDefault("weatherFragment", "");
        String vehicleFragment = fragments.getOrDefault("vehicleFragment", "");
        String scenarioFragment = fragments.getOrDefault("scenarioFragment", "");

        StringBuilder xml = new StringBuilder();

        // 1. Header XML Standard
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<OpenSCENARIO>\n");
        xml.append("  <FileHeader revMajor=\"1\" revMinor=\"0\" ")
                .append("date=\"").append(LocalDate.now()).append("\" ")
                .append("description=\"CARLA Scenario generated by CarlaConfigHub\" ")
                .append("author=\"CarlaConfigHub\"/>\n\n");

        // 2. RoadNetwork (Viene solo dallo Scenario)
        String roadNetwork = extractTagContent(scenarioFragment, "RoadNetwork");
        if (!roadNetwork.isEmpty()) {
            xml.append("  <RoadNetwork>\n")
                    .append(indent(roadNetwork, 4)).append("\n")
                    .append("  </RoadNetwork>\n\n");
        }

        // 3. ENTITIES (Unione di Veicolo Hero + Traffico dello Scenario)
        xml.append("  <Entities>\n");

        // Estrai entità dal fragment del veicolo (Ego)
        String egoEntities = extractTagContent(vehicleFragment, "Entities");
        xml.append(indent(egoEntities, 4)).append("\n");

        // Estrai entità dal fragment dello scenario (Traffico)
        String trafficEntities = extractTagContent(scenarioFragment, "Entities");
        xml.append(indent(trafficEntities, 4)).append("\n");

        xml.append("  </Entities>\n\n");

        // 4. STORYBOARD & INIT
        xml.append("  <Storyboard>\n");
        xml.append("    <Init>\n");
        xml.append("      <Actions>\n");

        // A. Meteo (Se arriva già formattato come GlobalAction)
        // Nota: Se il weatherFragment contiene solo <Weather>...</Weather>, va adattato.
        // Assumo che arrivi come <GlobalAction>... o simile, altrimenti lo stampiamo diretto.
        if (weatherFragment.contains("<GlobalAction") || weatherFragment.contains("<Private")) {
            xml.append(indent(weatherFragment, 8)).append("\n");
        } else {
            // Fallback se è solo il blocco Weather nudo e crudo
            xml.append(indent(weatherFragment, 8)).append("\n");
        }

        // B. Azioni Init del Veicolo (Posizionamento Ego)
        // Cerchiamo dentro <Init><Actions> ... </Actions></Init> o prendiamo tutto se è frammentario
        String vehicleInit = extractInitActions(vehicleFragment);
        xml.append(indent(vehicleInit, 8)).append("\n");

        // C. Azioni Init dello Scenario (Posizionamento Traffico)
        String scenarioInit = extractInitActions(scenarioFragment);
        xml.append(indent(scenarioInit, 8)).append("\n");

        xml.append("      </Actions>\n");
        xml.append("    </Init>\n");

        // 5. Story (Obbligatoria)
        xml.append("    <Story name=\"MainStory\">\n");
        xml.append("      <Act name=\"DefaultAct\"/>\n");
        xml.append("    </Story>\n");

        xml.append("  </Storyboard>\n");
        xml.append("</OpenSCENARIO>");

        String result = xml.toString();

        // Pulizia righe vuote extra (estetico)
        return result.replaceAll("(?m)^[ \t]*\r?\n", "");
    }

    // ---------------- Helper ----------------

    /**
     * Estrae il contenuto INTERNO a un tag specifico (es. tutto ciò che sta dentro <Entities>...</Entities>)
     * Gestisce tag multipli o nidificati estraendo tutto il blocco.
     */
    private String extractTagContent(String source, String tagName) {
        if (source == null || source.isEmpty()) return "";

        // Regex pattern: <TagName>(...contenuto...)</TagName>
        // (?s) abilita il DOTALL (il punto matcha anche a capo)
        Pattern pattern = Pattern.compile("<" + tagName + ">(.*?)</" + tagName + ">", Pattern.DOTALL);
        Matcher matcher = pattern.matcher(source);

        StringBuilder sb = new StringBuilder();
        while (matcher.find()) {
            sb.append(matcher.group(1)).append("\n");
        }
        return sb.toString().trim();
    }

    /**
     * Cerca di estrarre le azioni dentro <Init><Actions> ... </Actions></Init>
     * Se non trova la struttura completa, prova a cercare direttamente <Private> o <GlobalAction>
     */
    private String extractInitActions(String source) {
        if (source == null || source.isEmpty()) return "";

        // Provo a prendere il contenuto dentro <Actions> (che sta dentro Init)
        String actionsContent = extractTagContent(source, "Actions");

        if (!actionsContent.isEmpty()) {
            return actionsContent;
        }

        // Se il frammento non ha i tag <Init><Actions> ma contiene direttamente le azioni
        // (es. <Private... o <GlobalAction...) allora lo restituisco tutto, filtrando header/footer se presenti
        if (source.contains("<Private") || source.contains("<GlobalAction")) {
            // Rimuovi eventuali tag contenitori se presenti in modo disordinato
            String clean = source.replaceAll("<\\?xml.*?>", "")
                    .replaceAll("<OpenSCENARIO>", "")
                    .replaceAll("</OpenSCENARIO>", "")
                    .replaceAll("<Entities>.*?</Entities>", ""); // Rimuovi entità se sono rimaste
            return clean.trim();
        }

        return "";
    }

    private String indent(String xml, int spaces) {
        if (xml == null || xml.isBlank()) return "";
        String pad = " ".repeat(spaces);
        return xml.replaceAll("(?m)^", pad);
    }
}