package com.tirocinio.Scenario.service;

import org.springframework.stereotype.Service;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Random;

@Service
public class ScenarioService {

    private static final List<String> VALID_TOWNS = Arrays.asList(
            "Town01", "Town02", "Town03", "Town04", "Town05", "Town10HD"
    );

    private final Random random = new Random();

    public String generateScenarioFragment(Map<String, Object> params) {

        // --- 1. Parsing input ---
        String town = (String) params.get("town");
        Integer pedestrians = parseInteger(params.get("pedestrians"));
        Double trafficDensity = parseDouble(params.get("trafficDensity"));

        // --- 2. Validazione ---
        validateTown(town);
        validatePositiveInteger(pedestrians, "pedestrians");
        validatePercentage(trafficDensity, "trafficDensity");

        // --- 3. Calcolo numero veicoli ---
        int vehicleCount = mapTrafficDensityToVehicles(trafficDensity);

        // --- 4. Costruzione XML ---
        StringBuilder xml = new StringBuilder();

        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<OpenSCENARIO>\n");
        xml.append("  <FileHeader revMajor=\"1\" revMinor=\"0\" date=\"2025-12-29\" ")
                .append("description=\"Generated by CarlaConfigHub\" author=\"CarlaConfigHub\"/>\n\n");

        // --- Road Network ---
        xml.append("  <RoadNetwork>\n");
        xml.append("    <LogicFile filepath=\"").append(town).append("\"/>\n");
        xml.append("  </RoadNetwork>\n\n");


        xml.append("  <Entities>\n");

        for (int i = 0; i < vehicleCount; i++) {
            xml.append("    <ScenarioObject name=\"TrafficVehicle_").append(i).append("\">\n")
                    .append("      <Vehicle name=\"vehicle.tesla.model3\" vehicleCategory=\"car\">\n")
                    .append("        <BoundingBox>\n")
                    .append("          <Center x=\"1.5\" y=\"0.0\" z=\"0.9\"/>\n")
                    .append("          <Dimensions width=\"2.0\" length=\"4.5\" height=\"1.5\"/>\n")
                    .append("        </BoundingBox>\n")
                    .append("      </Vehicle>\n")
                    .append("    </ScenarioObject>\n");
        }

        xml.append("  </Entities>\n\n");

        // --- Storyboard ---
        xml.append("  <Storyboard>\n");
        xml.append("    <Init>\n");
        xml.append("      <Actions>\n");

        // --- Posizionamento veicoli del traffico ---
        for (int i = 0; i < vehicleCount; i++) {

            double randX = getRandomCoordinate(-50, 50);
            double randY = getRandomCoordinate(-200, -100); // Range corretto

            xml.append("        <Private entityRef=\"TrafficVehicle_").append(i).append("\">\n")
                    .append("          <PrivateAction>\n")
                    .append("            <TeleportAction>\n")
                    .append("              <Position>\n")
                    .append("                <WorldPosition x=\"").append(format(randX))
                    .append("\" y=\"").append(format(randY))
                    .append("\" z=\"0.5\" h=\"0.0\" p=\"0.0\" r=\"0.0\"/>\n")
                    .append("              </Position>\n")
                    .append("            </TeleportAction>\n")
                    .append("          </PrivateAction>\n")
                    .append("          <PrivateAction>\n")
                    .append("            <ControllerAction>\n")
                    .append("              <AssignControllerAction>\n")
                    .append("                <Controller name=\"carla_autopilot\"/>\n")
                    .append("              </AssignControllerAction>\n")
                    .append("            </ControllerAction>\n")
                    .append("          </PrivateAction>\n")
                    .append("        </Private>\n");
        }

        xml.append("      </Actions>\n");
        xml.append("    </Init>\n");

        xml.append("    <Story name=\"MainStory\">\n");
        xml.append("      <Act name=\"DefaultAct\"/>\n");
        xml.append("    </Story>\n");

        xml.append("  </Storyboard>\n");
        xml.append("</OpenSCENARIO>");

        return xml.toString();
    }

    // ---------------- Helper ----------------

    private double getRandomCoordinate(double min, double max) {
        return min + (max - min) * random.nextDouble();
    }

    private String format(double value) {
        return String.format("%.1f", value);
    }

    private void validateTown(String town) {
        if (town == null || !VALID_TOWNS.contains(town)) {
            throw new IllegalArgumentException("Mappa non valida o inesistente: " + town);
        }
    }

    private void validatePositiveInteger(Integer value, String fieldName) {
        if (value == null || value < 0) {
            throw new IllegalArgumentException("Il campo '" + fieldName + "' non può essere negativo.");
        }
    }

    private void validatePercentage(Double value, String fieldName) {
        if (value == null || value < 0.0 || value > 100.0) {
            throw new IllegalArgumentException("Il campo '" + fieldName + "' deve essere tra 0 e 100.");
        }
    }

    private Integer parseInteger(Object value) {
        try {
            return value == null ? 0 : Integer.parseInt(value.toString());
        } catch (Exception e) {
            return 0;
        }
    }

    private Double parseDouble(Object value) {
        try {
            return value == null ? 0.0 : Double.parseDouble(value.toString());
        } catch (Exception e) {
            return 0.0;
        }
    }

    private int mapTrafficDensityToVehicles(Double density) {
        if (density < 10) return 2;
        if (density < 30) return 5;
        if (density < 60) return 10;
        if (density < 80) return 20;
        return 30;
    }
}
