package com.tirocinio.Scenario.service;

import org.springframework.stereotype.Service;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Random;

@Service
public class ScenarioService {

    private static final List<String> VALID_TOWNS = Arrays.asList(
            "Town01", "Town02", "Town03", "Town04", "Town05", "Town10HD"
    );

    // Generatore di numeri casuali per le posizioni
    private final Random random = new Random();

    public String generateScenarioFragment(Map<String, Object> params) {

        // 1. Parsing input
        String town = (String) params.get("town");
        Integer pedestrians = parseInteger(params.get("pedestrians"));
        Double trafficDensity = parseDouble(params.get("trafficDensity"));

        // 2. Validazione
        validateTown(town);
        validatePositiveInteger(pedestrians, "pedestrians");
        validatePercentage(trafficDensity, "trafficDensity");

        // 3. Calcolo numero veicoli
        int vehicleCount = mapTrafficDensityToVehicles(trafficDensity);

        // 4. Inizio costruzione XML Completo
        StringBuilder xml = new StringBuilder();

        // Header standard OpenSCENARIO
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<OpenSCENARIO>\n");
        xml.append("  <FileHeader revMajor=\"1\" revMinor=\"0\" date=\"2025-12-29\" description=\"Generated by CarlaConfigHub\" author=\"CarlaConfigHub\"/>\n\n");

        // ---- Road Network ----
        xml.append("  <RoadNetwork>\n");
        xml.append("    <LogicFile filepath=\"").append(town).append("\"/>\n");
        xml.append("  </RoadNetwork>\n\n");

        // ---- A. SEZIONE ENTITIES (Definizioni) ----
        xml.append("  <Entities>\n");

        // 1. Ego Vehicle (L'auto principale)
        xml.append("    <ScenarioObject name=\"EgoVehicle\">\n");
        xml.append("      <Vehicle name=\"vehicle.audi.etron\" vehicleCategory=\"car\">\n");
        xml.append("        <BoundingBox>\n");
        xml.append("          <Center x=\"1.5\" y=\"0.0\" z=\"0.9\"/>\n");
        xml.append("          <Dimensions width=\"2.0\" length=\"4.5\" height=\"1.5\"/>\n");
        xml.append("        </BoundingBox>\n");
        xml.append("      </Vehicle>\n");
        xml.append("    </ScenarioObject>\n");

        // 2. Traffic Vehicles (Generati col ciclo)
        for (int i = 0; i < vehicleCount; i++) {
            xml.append("    <ScenarioObject name=\"TrafficVehicle_").append(i).append("\">\n");
            // Usiamo un modello standard per il traffico (es. Tesla Model 3)
            xml.append("      <Vehicle name=\"vehicle.tesla.model3\" vehicleCategory=\"car\">\n");
            xml.append("        <BoundingBox>\n");
            xml.append("          <Center x=\"1.5\" y=\"0.0\" z=\"0.9\"/>\n");
            xml.append("          <Dimensions width=\"2.0\" length=\"4.5\" height=\"1.5\"/>\n");
            xml.append("        </BoundingBox>\n");
            xml.append("      </Vehicle>\n");
            xml.append("    </ScenarioObject>\n");
        }
        xml.append("  </Entities>\n\n");

        // ---- B. SEZIONE STORYBOARD (Azioni e Posizionamento) ----
        xml.append("  <Storyboard>\n");
        xml.append("    <Init>\n");
        xml.append("      <Actions>\n");

        // 1. Meteo (Environment)
        xml.append("        <GlobalAction>\n");
        xml.append("          <EnvironmentAction>\n");
        xml.append("            <Environment>\n");
        xml.append("              <Weather>\n");
        xml.append("                <Sun azimuth=\"0\" elevation=\"45.0\"/>\n"); // Default o parametrico
        xml.append("                <Precipitation precipitationType=\"rain\" intensity=\"0.0\"/>\n");
        xml.append("              </Weather>\n");
        xml.append("            </Environment>\n");
        xml.append("          </EnvironmentAction>\n");
        xml.append("        </GlobalAction>\n");

        // 2. Posizionamento Ego Vehicle (Punto fisso sicuro)
        xml.append("        <Private entityRef=\"EgoVehicle\">\n");
        xml.append("          <PrivateAction>\n");
        xml.append("            <TeleportAction>\n");
        xml.append("              <Position>\n");
        xml.append("                <WorldPosition x=\"-10.0\" y=\"-150.0\" z=\"0.5\" h=\"0.0\" p=\"0.0\" r=\"0.0\"/>\n");
        xml.append("              </Position>\n");
        xml.append("            </TeleportAction>\n");
        xml.append("          </PrivateAction>\n");
        xml.append("          <PrivateAction>\n");
        xml.append("            <ControllerAction>\n");
        xml.append("              <AssignControllerAction>\n");
        xml.append("                <Controller name=\"carla_autopilot\"/>\n");
        xml.append("              </AssignControllerAction>\n");
        xml.append("            </ControllerAction>\n");
        xml.append("          </PrivateAction>\n");
        xml.append("        </Private>\n");

        // 3. Posizionamento Traffic Vehicles (Ciclo con coordinate random)
        for (int i = 0; i < vehicleCount; i++) {
            // Genera coordinate casuali intorno all'area (evitando l'Ego vehicle)
            double randX = getRandomCoordinate(-50, 50);
            double randY = getRandomCoordinate(-100, -200); // Zona diversa da Ego

            xml.append("        <Private entityRef=\"TrafficVehicle_").append(i).append("\">\n");
            xml.append("          <PrivateAction>\n");
            xml.append("            <TeleportAction>\n");
            xml.append("              <Position>\n");
            xml.append("                <WorldPosition x=\"").append(String.format("%.1f", randX))
                    .append("\" y=\"").append(String.format("%.1f", randY))
                    .append("\" z=\"0.5\" h=\"0.0\" p=\"0.0\" r=\"0.0\"/>\n");
            xml.append("              </Position>\n");
            xml.append("            </TeleportAction>\n");
            xml.append("          </PrivateAction>\n");
            xml.append("          <PrivateAction>\n");
            xml.append("            <ControllerAction>\n");
            xml.append("              <AssignControllerAction>\n");
            xml.append("                <Controller name=\"carla_autopilot\"/>\n");
            xml.append("              </AssignControllerAction>\n");
            xml.append("            </ControllerAction>\n");
            xml.append("          </PrivateAction>\n");
            xml.append("        </Private>\n");
        }

        xml.append("      </Actions>\n");
        xml.append("    </Init>\n");

        // Parte finale standard
        xml.append("    <Story name=\"MainStory\">\n");
        xml.append("      <Act name=\"DefaultAct\"/>\n");
        xml.append("    </Story>\n");
        xml.append("  </Storyboard>\n");
        xml.append("</OpenSCENARIO>");

        return xml.toString();
    }

    // ---------------- Helper ----------------

    // Genera un numero casuale tra min e max
    private double getRandomCoordinate(double min, double max) {
        return min + (max - min) * random.nextDouble();
    }

    private void validateTown(String town) {
        if (town == null || !VALID_TOWNS.contains(town)) {
            throw new IllegalArgumentException("Mappa non valida o inesistente: " + town);
        }
    }

    private void validatePositiveInteger(Integer value, String fieldName) {
        if (value < 0) throw new IllegalArgumentException("Il campo '" + fieldName + "' non può essere negativo.");
    }

    private void validatePercentage(Double value, String fieldName) {
        if (value < 0.0 || value > 100.0) throw new IllegalArgumentException("Il campo '" + fieldName + "' deve essere tra 0 e 100.");
    }

    private Integer parseInteger(Object value) {
        if (value == null) return 0;
        try { return Integer.valueOf(value.toString()); } catch (NumberFormatException e) { return 0; }
    }

    private Double parseDouble(Object value) {
        if (value == null) return 0.0;
        try { return Double.valueOf(value.toString()); } catch (NumberFormatException e) { return 0.0; }
    }

    private int mapTrafficDensityToVehicles(Double density) {
        if (density < 10) return 2;
        if (density < 30) return 5;
        if (density < 60) return 10;
        if (density < 80) return 20;
        return 30; // Max veicoli per non appesantire troppo
    }
}
